
#include "head.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>



void Instructions()
{
	int x = 0;
	printf("\n\n\nSix colours have been used in this game. A random combination of these colours is generated at every attempt of the game. Your aim is to figure out this combination in order, to win, in just 12 attempts.\n\n");
	printf("	***** Instructions: How to play! ***** \n\n");
	printf("1. The game will generate a combination of 4 numbers which will be unknown to you.\n\n"); 
	printf("2. The numbers will be between 1 to 6. Type in four numbers between 1 to 6.\n\n");
	printf("3. If your number matches to the numbers generated by game, it will display 'W'.\n\n");
	printf("4. If your number matches the number generated and is in the correct position, the game will display 'B'.\n\n\n");
	printf("5. You have 12 tries before you get the correct answer or else the game is over.\n\n");
//	printf("\n\n\nGet going, Good Luck!\););
	while(1)
	{
		printf("\n\nPress 1 to continue . . . ");
		scanf("%d", &x);
		switch(x)
		{
			case 1:
				main();
				break;
			default:
				printf("\nWrong Input!");
			
		}
	}
}
